
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
    - npm install
    - unset CI 
    - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2ca12db5a22b4ba9970cb28424080cc4af7989fc
  local_dir: build
  on:
    branch: master